import React, { useState } from 'react';
import { InvestigationReport } from '../types';
import { VerdictBadge } from './VerdictBadge';
import {
  Download,
  Share2,
  Copy,
  Check,
  FileCode,
  FileText,
  Printer,
  X,
  ShieldCheck,
  ExternalLink,
  Calendar,
  Layers,
  Sparkles
} from 'lucide-react';

interface ReportGeneratorModalProps {
  report: InvestigationReport;
  isOpen: boolean;
  onClose: () => void;
}

export const ReportGeneratorModal: React.FC<ReportGeneratorModalProps> = ({
  report,
  isOpen,
  onClose,
}) => {
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedCard, setCopiedCard] = useState(false);

  if (!isOpen) return null;

  const handleCopyLink = async () => {
    const url = `${window.location.origin}/?verify=${report.verificationId}`;
    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(url);
      }
    } catch {
      // Fallback
    }
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  };

  const handleCopySummaryCard = async () => {
    const summaryCardText = `🛡️ TRUTHLENS AI VERIFICATION REPORT\n` +
      `Claim: "${report.claim}"\n` +
      `Verdict: ${report.verdict.replace(/_/g, ' ')} (${report.confidenceScore}% Corroboration)\n` +
      `30-Sec Summary: ${report.summary30Sec}\n` +
      `Verification ID: ${report.verificationId}\n` +
      `Timestamp: ${new Date(report.timestamp).toUTCString()}\n` +
      `Verify before you believe: ${window.location.origin}/?verify=${report.verificationId}`;

    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(summaryCardText);
      }
    } catch {
      // Fallback
    }
    setCopiedCard(true);
    setTimeout(() => setCopiedCard(false), 2000);
  };

  const handleDownloadJSON = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(report, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `truthlens-${report.verificationId}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const handleDownloadMarkdown = () => {
    const mdContent = `# TRUTHLENS AI CREDIBILITY INTELLIGENCE DOSSIER
**Verification ID**: ${report.verificationId}  
**Timestamp**: ${report.timestamp}  
**Claim Evaluated**: "${report.claim}"  
**Verdict**: ${report.verdict}  
**Evidence Confidence Score**: ${report.confidenceScore}%  

---

## 30-Second Executive Summary
${report.summary30Sec}

---

## Detailed Investigation Breakdown
${report.detailedInvestigation}

---

## Expert Forensic & Evidence View
${report.expertEvidenceView}

---

## Sources Evaluated
${report.sources.map(s => `- **${s.name}** (${s.domain}) | Reputation: ${s.reputationTier} | Stance: ${s.stance} | Credibility: ${s.credibilityScore}/100\n  - *Excerpt*: "${s.quoteOrSummary}"`).join('\n\n')}

---

## Epistemic Limitations
${report.limitations.map(l => `- ${l}`).join('\n')}

*Generated by TruthLens AI • "Verify Before You Believe"*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `truthlens-${report.verificationId}.md`;
    document.body.appendChild(a);
    a.click();
    a.remove();
  };

  const handlePrint = () => {
    try {
      window.print();
    } catch (e) {
      console.warn('Printing in iframe is restricted:', e);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="glass-panel-glow rounded-2xl border border-slate-700 bg-slate-950 w-full max-w-2xl max-h-[90vh] flex flex-col overflow-hidden shadow-2xl">
        {/* Modal Header */}
        <div className="p-4 border-b border-slate-800 flex items-center justify-between bg-slate-900/80">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-400">
              <ShieldCheck className="w-4 h-4" />
            </div>
            <div>
              <h3 className="font-mono text-sm font-bold text-slate-100">
                Official Credibility Intelligence Dossier
              </h3>
              <p className="text-[11px] font-mono text-cyan-400">
                Audit Hash: {report.verificationId}
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-slate-100 rounded-lg hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="flex-1 overflow-y-auto p-5 space-y-5">
          {/* Printable Report Card Preview */}
          <div className="p-5 rounded-xl bg-slate-900 border border-slate-800 space-y-4">
            <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2">
                <VerdictBadge verdict={report.verdict} size="md" />
                <span className="text-xs font-mono font-bold text-cyan-400">
                  {report.confidenceScore}% Corroboration
                </span>
              </div>
              <span className="text-[11px] font-mono text-slate-400 flex items-center gap-1">
                <Calendar className="w-3 h-3 text-slate-500" />
                {new Date(report.timestamp).toLocaleDateString()}
              </span>
            </div>

            <div>
              <span className="text-[10px] font-mono uppercase tracking-wider text-slate-400 block mb-1">
                Investigated Assertion:
              </span>
              <h4 className="text-sm font-bold text-slate-100 font-mono">
                "{report.claim}"
              </h4>
            </div>

            <div>
              <span className="text-[10px] font-mono uppercase tracking-wider text-slate-400 block mb-1">
                Verified Bottom Line:
              </span>
              <p className="text-xs text-slate-300 leading-relaxed bg-slate-950/60 p-3 rounded-lg border border-slate-800/80">
                {report.summary30Sec}
              </p>
            </div>

            <div className="grid grid-cols-2 gap-2 text-xs font-mono text-slate-400 pt-2 border-t border-slate-800">
              <div>
                Sources Evaluated: <span className="text-slate-200 font-bold">{report.sources.length} nodes</span>
              </div>
              <div>
                Category: <span className="text-slate-200 font-bold">{report.category}</span>
              </div>
            </div>
          </div>

          {/* Export & Sharing Options */}
          <div className="space-y-3">
            <h4 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-400">
              Export & Verification Distribution:
            </h4>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {/* Copy Summary Card */}
              <button
                onClick={handleCopySummaryCard}
                className="flex items-center justify-between p-3 rounded-xl bg-slate-900 hover:bg-slate-850 border border-slate-800 hover:border-cyan-500 text-xs font-mono text-slate-200 transition-all"
              >
                <span className="flex items-center gap-2">
                  <Copy className="w-4 h-4 text-cyan-400" />
                  Copy Shareable Card
                </span>
                {copiedCard ? <Check className="w-4 h-4 text-emerald-400" /> : <span className="text-slate-500 text-[10px]">Text</span>}
              </button>

              {/* Copy Verification Link */}
              <button
                onClick={handleCopyLink}
                className="flex items-center justify-between p-3 rounded-xl bg-slate-900 hover:bg-slate-850 border border-slate-800 hover:border-cyan-500 text-xs font-mono text-slate-200 transition-all"
              >
                <span className="flex items-center gap-2">
                  <Share2 className="w-4 h-4 text-cyan-400" />
                  Copy Permanent URL
                </span>
                {copiedLink ? <Check className="w-4 h-4 text-emerald-400" /> : <span className="text-slate-500 text-[10px]">Link</span>}
              </button>

              {/* Download JSON */}
              <button
                onClick={handleDownloadJSON}
                className="flex items-center justify-between p-3 rounded-xl bg-slate-900 hover:bg-slate-850 border border-slate-800 hover:border-cyan-500 text-xs font-mono text-slate-200 transition-all"
              >
                <span className="flex items-center gap-2">
                  <FileCode className="w-4 h-4 text-purple-400" />
                  Export Machine JSON
                </span>
                <Download className="w-4 h-4 text-slate-500" />
              </button>

              {/* Download Markdown */}
              <button
                onClick={handleDownloadMarkdown}
                className="flex items-center justify-between p-3 rounded-xl bg-slate-900 hover:bg-slate-850 border border-slate-800 hover:border-cyan-500 text-xs font-mono text-slate-200 transition-all"
              >
                <span className="flex items-center gap-2">
                  <FileText className="w-4 h-4 text-emerald-400" />
                  Download Markdown Dossier
                </span>
                <Download className="w-4 h-4 text-slate-500" />
              </button>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-800 bg-slate-900/80 flex items-center justify-between">
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-mono transition-colors"
          >
            <Printer className="w-4 h-4" />
            Print Official PDF
          </button>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold font-mono text-xs transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
